version: 2.1

orbs:
  codacy: codacy/base@2.14.8

workflows:
  version: 2
  test-and-publish:
    jobs:
      - codacy/checkout_and_version
      - codacy/publish_ghr:
          path: ~/workdir
          requires:
            - codacy/checkout_and_version
